# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voicera-backend
    ports:
      - "5000:5000"
    volumes:
      # Mount models directory (so you don't rebuild Docker image when retraining)
      - ./backend/app/models:/app/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voicera-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.18.153.187:5000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  models: